### ISSUE TITLE
Unable to signup locally

### ISSUE THREAD

**Issue by craigstanton** [Gottwik/legolabels#2]
After downloading the code and running 'npm install' and 'npm run', I tried to sign up with a username of 'craig@test.com' and a 14 character password. The signup failed and the console showed the following message

Error: ENAMETOOLONG: name too long, stat '/Users/stantonca/Documents/Development/personal/legolabels/_src/user_logged_in?user=%7B%22email_verified%22:false,%22email%22:%22craig@test.com%22,%22clientID%22:%22AtVGcLisv5hrs32LGSbJt2oBACFSn9OJ%22,%22updated_at%22:%222017-01-18T00:02:26.268Z%22,%22name%22:%22craig@test.com%22,%22picture%22:%22https:%2F%2Fs.gravatar.com%2Favatar%2F3cb60126ff4c803b46fc32157822b7bb%3Fs%3D480%26r%3Dpg%26d%3Dhttps%253A%252F%252Fcdn.auth0.com%252Favatars%252Fcr.png%22,%22user_id%22:%22auth0%7C587eb090f299cf16c0558dce%22,%22nickname%22:%22craig%22,%22identities%22:%5B%7B%22user_id%22:%22587eb090f299cf16c0558dce%22,%22provider%22:%22auth0%22,%22connection%22:%22Username-Password-Authentication%22,%22isSocial%22:false%7D%5D,%22created_at%22:%222017-01-18T00:02:24.679Z%22,%22sub%22:%22auth0%7C587eb090f299cf16c0558dce%22%7D.html'

It also occurred with shorter passwords and rejected non-email based user names

**Comment by Gottwik** [comment]
I managed to reproduce this, but it is related to the mixup of localhost:3000 and localhost:5000. Could you pull and run `npm i` and see if it persist?
