### ISSUE TITLE
Correct project title htttp://www.bricklabels.com/ to http://www.bricklabels.com/

### ISSUE THREAD

**Issue by daitangio** [Gottwik/legolabels#4]
Project description url has ha typo.

**Comment by Gottwik** [comment]
Nice catch! Fixed it thank you.

**Comment by Gottwik** [comment]
Hey @daitangio would you please let me know if you find any other bugs?

**Comment by daitangio** [comment]
For sure. Mongo is required? I think removing it would help spreading the project.

Please excuse typs as Sent from my iPhone 7

**Comment by Gottwik** [comment]
Well, the parts to be printed has to be stored somewhere and I use heroku with no persistent storage so some storage is required. But mlab is free and works flawlessly. Do you have any suggestions for alternative?

**Comment by daitangio** [comment]
Is it possible to store them in a json file for "db-less" configuration? As a configuration option. I think it will increase probability someone with little time (like me) will be able to run the code. It will be slower to find pieces, but it is okey I suppose.

**Comment by Gottwik** [comment]
Yea, that would be ideal, but with heroku each time you restart you would lose all this data. Hey, try the mlab.com, you just sign up, add the connection string to enduro_secret.json and you should be good to go.
