### ISSUE TITLE
bricklabels.com not possible to add elements

### ISSUE THREAD

**Issue by moustic999** [Gottwik/legolabels#5]
I tested on bricklabels.com but when I enter a part number, the moving blue brick remains infinitely and parts are never added.

So that doesn't work.

**Comment by Gottwik** [comment]
Hey @moustic999, Thanks for notifying me. The rebrickable api key was missing from the heroku deployment. Should be good to go now.

![image](https://cloud.githubusercontent.com/assets/277311/23019133/1efc905e-f441-11e6-89d3-30418042cc14.png)
